# Configuration for project phyexdb, connector PhyExDB

# Learn more about the Teamscale IDE Configuration File Format at
# <https://docs.teamscale.com/reference/teamscale-toml/>.

version = "1.0"

root = true

[server]
url = "https://teamscale.niklhut.de/"

[project]
id = "phyexdb"