services:
  backend:
    image: ghcr.io/phyexdb/phyexdb:latest
    container_name: phyexdb_backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - public_data:/app/public
    ports:
      - 8080:8080

  db:
    image: postgres:17-alpine
    container_name: phyexdb_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  migrate:
    image: phyexdb
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - tools
    command: sh -c "node /app/migrations/migrate.js && node /app/migrations/seed.js"

  migration-status:
    image: phyexdb
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - tools
    command: node /app/migrations/migrationStatus.js

  revert:
    image: phyexdb
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - tools
    command: node /app/migrations/revert.js



volumes:
  db_data:
  public_data:
