services:
  phyexdb:
    image: ${APP_IMAGE:-ghcr.io/phyexdb/phyexdb}:${APP_TAG:-latest}
    container_name: ${APP_NAME:-phyexdb}_phyexdb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - public_data:/app/public

  db:
    image: postgres:${POSTGRES_TAG:-17-alpine}
    container_name: ${APP_NAME:-phyexdb}_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  proxy:
    image: nginx:latest
    container_name: ${APP_NAME:-phyexdb}_proxy
    restart: unless-stopped
    depends_on:
      - phyexdb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - public_data:/app/public:ro
      # Include the following line if you want to use SSL
      # But this also needs to be configured in nginx.conf
      # - /etc/ssl:/etc/ssl:ro

volumes:
  db_data:
  public_data:
