services:
  backend:
    image: ${APP_IMAGE:-ghcr.io/phyexdb/phyexdb}:${APP_TAG:-latest}
    container_name: ${APP_NAME:-phyexdb}_backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - public_data:/app/public
    ports:
      - 8080:8080

  db:
    image: postgres:${POSTGRES_TAG:-17-alpine}
    container_name: ${APP_NAME:-phyexdb}_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  db_data:
  public_data:
